import DefaultTags from "./DefaultTags";

export default function Head() {
  return (
    <>
      <DefaultTags />
      <title>El Villanense - Portal de noticias</title>
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
