import DefaultTags from "../../DefaultTags";

export default function Head({ params }) {
  return (
    <>
      <DefaultTags />
      <title>{params.id}</title>
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
